# Form implementation generated from reading ui file './searchWinNew.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 300)
        MainWindow.setMinimumSize(QtCore.QSize(403, 300))
        MainWindow.setMaximumSize(QtCore.QSize(403, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 18))
        self.label.setObjectName("label")
        self.lowestPrice = QtWidgets.QSpinBox(self.centralwidget)
        self.lowestPrice.setGeometry(QtCore.QRect(20, 40, 361, 27))
        self.lowestPrice.setMaximum(1000000000)
        self.lowestPrice.setObjectName("lowestPrice")
        self.highestPrice = QtWidgets.QSpinBox(self.centralwidget)
        self.highestPrice.setGeometry(QtCore.QRect(20, 100, 361, 27))
        self.highestPrice.setMaximum(1000000000)
        self.highestPrice.setObjectName("highestPrice")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 61, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 61, 18))
        self.label_3.setObjectName("label_3")
        self.lowestSize = QtWidgets.QSpinBox(self.centralwidget)
        self.lowestSize.setGeometry(QtCore.QRect(20, 160, 361, 27))
        self.lowestSize.setMaximum(1000)
        self.lowestSize.setObjectName("lowestSize")
        self.useLowestPrice = QtWidgets.QCheckBox(self.centralwidget)
        self.useLowestPrice.setGeometry(QtCore.QRect(281, 18, 101, 24))
        self.useLowestPrice.setObjectName("useLowestPrice")
        self.useHighestPrice = QtWidgets.QCheckBox(self.centralwidget)
        self.useHighestPrice.setGeometry(QtCore.QRect(281, 78, 101, 24))
        self.useHighestPrice.setObjectName("useHighestPrice")
        self.useLowestSize = QtWidgets.QCheckBox(self.centralwidget)
        self.useLowestSize.setGeometry(QtCore.QRect(281, 138, 101, 24))
        self.useLowestSize.setObjectName("useLowestSize")
        self.highestSize = QtWidgets.QSpinBox(self.centralwidget)
        self.highestSize.setGeometry(QtCore.QRect(20, 220, 361, 27))
        self.highestSize.setMaximum(1000)
        self.highestSize.setObjectName("highestSize")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 61, 18))
        self.label_4.setObjectName("label_4")
        self.useHighestSize = QtWidgets.QCheckBox(self.centralwidget)
        self.useHighestSize.setGeometry(QtCore.QRect(281, 198, 101, 24))
        self.useHighestSize.setObjectName("useHighestSize")
        self.apply = QtWidgets.QPushButton(self.centralwidget)
        self.apply.setGeometry(QtCore.QRect(300, 260, 80, 26))
        self.apply.setObjectName("apply")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(20, 260, 80, 26))
        self.reset.setObjectName("reset")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "搜尋條件"))
        self.label.setText(_translate("MainWindow", "最低價格"))
        self.label_2.setText(_translate("MainWindow", "最高價格"))
        self.label_3.setText(_translate("MainWindow", "最低坪數"))
        self.useLowestPrice.setText(_translate("MainWindow", "使用最低價格"))
        self.useHighestPrice.setText(_translate("MainWindow", "使用最高價格"))
        self.useLowestSize.setText(_translate("MainWindow", "使用最低坪數"))
        self.label_4.setText(_translate("MainWindow", "最高坪數"))
        self.useHighestSize.setText(_translate("MainWindow", "使用最高坪數"))
        self.apply.setText(_translate("MainWindow", "確認"))
        self.reset.setText(_translate("MainWindow", "重置"))
